{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "77d162ff",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# ---------------------------------------------------------\n",
    "# 1. 6가지 기본 커널 함수 정의\n",
    "# ---------------------------------------------------------\n",
    "def kernel_constant(t, c=1.0):\n",
    "    return np.full((len(t), len(t)), c)\n",
    "\n",
    "def kernel_white_noise(t, sigma_n=0.5):\n",
    "    return np.eye(len(t)) * (sigma_n ** 2)\n",
    "\n",
    "def kernel_linear(t, sigma=1.0):\n",
    "    # 정규화된 시간 축 사용 (0 ~ 1)\n",
    "    t_norm = (t - np.mean(t)) / np.std(t)\n",
    "    return (sigma ** 2) + np.outer(t_norm, t_norm)\n",
    "\n",
    "def kernel_rbf(t, length_scale=20.0):\n",
    "    dist_sq = (t[:, None] - t[None, :]) ** 2\n",
    "    return np.exp(-dist_sq / (2.0 * (length_scale ** 2)))\n",
    "\n",
    "def kernel_rational_quadratic(t, alpha=0.5, length_scale=20.0):\n",
    "    dist_sq = (t[:, None] - t[None, :]) ** 2\n",
    "    return (1.0 + dist_sq / (2.0 * alpha * (length_scale ** 2))) ** (-alpha)\n",
    "\n",
    "def kernel_periodic(t, period=40.0, length_scale=1.0):\n",
    "    diff = np.abs(t[:, None] - t[None, :])\n",
    "    sin_term = np.sin(np.pi * diff / period)\n",
    "    return np.exp(-2.0 * (sin_term ** 2) / (length_scale ** 2))\n",
    "\n",
    "# ---------------------------------------------------------\n",
    "# 2. GP Prior 샘플링 함수\n",
    "# ---------------------------------------------------------\n",
    "def sample_from_gp(cov_matrix, num_samples=3, jitter=1e-5):\n",
    "    length = cov_matrix.shape[0]\n",
    "    # 수치적 안정성을 위해 대각선에 작은 jitter 추가\n",
    "    K = cov_matrix + np.eye(length) * jitter\n",
    "    mean = np.zeros(length)\n",
    "    return np.random.multivariate_normal(mean, K, size=num_samples)\n",
    "\n",
    "# ---------------------------------------------------------\n",
    "# 3. 6개 커널별 시계열 시각화\n",
    "# ---------------------------------------------------------\n",
    "np.random.seed(42)\n",
    "T = 200\n",
    "t = np.linspace(0, T - 1, T)\n",
    "\n",
    "kernels = [\n",
    "    (\"1. Constant Kernel (기준 레벨)\", kernel_constant(t)),\n",
    "    (\"2. White Noise Kernel (잡음)\", kernel_white_noise(t, sigma_n=0.3)),\n",
    "    (\"3. Linear Kernel (상승/하강 추세)\", kernel_linear(t, sigma=1.0)),\n",
    "    (\"4. RBF Kernel (부드러운 곡선)\", kernel_rbf(t, length_scale=15.0)),\n",
    "    (\"5. Rational Quadratic Kernel (다중 스케일 곡선)\", kernel_rational_quadratic(t, alpha=0.2, length_scale=15.0)),\n",
    "    (\"6. Periodic Kernel (주기적 계절성, p=40)\", kernel_periodic(t, period=40.0))\n",
    "]\n",
    "\n",
    "fig, axes = plt.subplots(3, 2, figsize=(15, 10), sharex=True)\n",
    "axes = axes.flatten()\n",
    "\n",
    "for idx, (title, cov) in enumerate(kernels):\n",
    "    ax = axes[idx]\n",
    "    samples = sample_from_gp(cov, num_samples=3)\n",
    "    for s_idx, sample in enumerate(samples):\n",
    "        ax.plot(t, sample, label=f\"Sample {s_idx + 1}\" if idx == 0 else \"\")\n",
    "    ax.set_title(title, fontsize=12, fontweight=\"bold\")\n",
    "    ax.grid(True, linestyle=\"--\", alpha=0.5)\n",
    "\n",
    "axes[0].legend(loc=\"upper right\")\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "(Dissertation) (3.13.2.final.0)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.13.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
